#!/usr/bin/env python
# -*- coding: utf-8 -*-
# author：albert time:2019/5/12

import tkinter
from tkinter import *

###创建横条型框架
def frame(root,side):
    f=Frame(root)
    f.pack(side=side,expand=YES,fill=BOTH)
    return f

####统一定义按钮样式与风格
def button(root,side,text,command=None):
    btn=Button(root,text=text,font=('宋体',12),command=command)
    btn.pack(side=side,expand=YES,fill=BOTH)
    return btn

####初始化页面布局
class Calculator(Frame):
    def __init__(self):
        Frame.__init__(self)
        self.pack(expand=YES,fill=BOTH)
        self.master.title('简易计算器')
        display=StringVar()

        Entry(self,relief=SUNKEN,font=('宋体','20','bold'),textvariable=display).pack(side=TOP,expand=YES,fill=BOTH)

        clearF=frame(self,TOP)
        button(clearF ,LEFT,'清除',lambda w=display : w.set(''))

        ###添加按钮和条形框
        for key in ("123+","456-","789*",".0=/"):
            keyF=frame(self,TOP)
            for char in key:
                if char == '=':
                    btn=button(keyF,LEFT,char)
                    btn.bind('<ButtonRelease - 1>',lambda e, s=self, w=display:s.calc(w),'+')
                else:
                    btn=button(keyF,LEFT,char,lambda w=display, c=char:w.set(w.get()+c))

    #####调用eval函数计算表达式的值
    def calc(self,display):
        try:
            display.set(eval(display.get()))
        except:
            display.set("ERROR")


if __name__=='__main__':
    print('ok')
    Calculator().mainloop()
